name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v
  parallel-mac-job:
    runs-on: macos-latest
    steps:
      - name: Checks Sw version
        run: sw_vers
  dependant-windows-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "windows String"
      - name: Error Step
        run: SomeRandom
