name: workflow Commands
on: [push]

jobs:
  workflow-cmds-mac:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash commands
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  workflow-cmds-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Run pwsl commands
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
